### ISSUE TITLE
Button display issue

### ISSUE THREAD

**Issue by LeandroTorresSicilia** [reiniergs/react-lightning-components#28]
When a Button component is created without neither children and label like this:
```html
<Button />
```
The result is:

![1](https://user-images.githubusercontent.com/24737097/27807070-795730fe-600c-11e7-86ae-c408a90fedb2.png)

We should pass a fallback label in order to solve this.

**Comment by reiniergs** [comment]
is it a question? if so the answer is No, we can not fallback to any label, because don't own the content .. it's something that consumer has to provide. What we can do I think is if the consumer of the button does not pass label or children we do console.error saying `Either the label or children are required.`
